import { resolve, relative, basename, dirname } from "node:path";
import { globSync } from "glob";
import { parseMarkdown, type ParseWarning } from "../parsers/markdown.js";
import { createTSParser } from "../parsers/typescript.js";
import type { ArtifactGraph, GraphNode, GraphEdge, SpectraceConfig } from "../types.js";

export interface BuildWarning {
  type: "duplicate-id" | "ambiguous-id" | "orphan-doc" | "invalid-relation" | "reserved-prefix";
  id: string;
  files: string[];
  message?: string;
}

interface CollectedReq {
  id: string;
  specDir: string;
  node: GraphNode;
  edges: GraphEdge[];
}

export function buildGraph(
  rootDir: string,
  config: SpectraceConfig,
): { graph: ArtifactGraph; warnings: BuildWarning[] } {
  const nodes = new Map<string, GraphNode>();
  const edges: GraphEdge[] = [];
  const warnings: BuildWarning[] = [];

  const specFiles = config.specDirs.flatMap((dir) => globSync(resolve(rootDir, dir, "**/*.md")));

  const autoNodes = config.docGraph?.autoNodes ?? true;
  const autoContains = config.docGraph?.autoContains ?? true;
  const RESERVED_PREFIXES = ["doc:", "file:", "test:", "symbol:"];
  const parseWarnings: ParseWarning[] = [];

  // Pass 1: collect all req nodes and detect collisions
  const collected: CollectedReq[] = [];
  const nonReqNodes: GraphNode[] = [];
  const nonReqEdges: GraphEdge[] = [];

  for (const file of specFiles) {
    const result = parseMarkdown(file, rootDir);
    const relFile = relative(rootDir, file);
    const specDir = extractSpecDir(relFile, config.specDirs);

    // Collect parse warnings
    parseWarnings.push(...result.warnings);

    for (const node of result.nodes) {
      if (node.kind === "req") {
        // T028: reserved-prefix warning
        if (RESERVED_PREFIXES.some((p) => node.id.startsWith(p))) {
          const prefix = RESERVED_PREFIXES.find((p) => node.id.startsWith(p))!;
          warnings.push({
            type: "reserved-prefix",
            id: node.id,
            files: [node.filePath],
            message: `req ID uses reserved prefix "${prefix}". This may conflict with auto-generated node IDs`,
          });
        }
        collected.push({ id: node.id, specDir, node, edges: [] });
      } else if (node.kind === "doc") {
        // T027: autoNodes filter - if disabled and no explicit node_id
        // Auto-generated IDs have the format `doc:<filePath>`
        const isAutoGenerated = node.id === `doc:${node.filePath}`;
        if (!autoNodes && isAutoGenerated) {
          continue; // Skip auto-generated doc nodes when autoNodes is false
        }
        nonReqNodes.push(node);
      } else {
        nonReqNodes.push(node);
      }
    }

    for (const edge of result.edges) {
      const isFromReq = collected.some((c) => c.node.id === edge.source || c.id === edge.source);
      if (isFromReq) {
        const req = collected.find((c) => c.node.id === edge.source || c.id === edge.source);
        if (req) req.edges.push(edge);
      } else {
        nonReqEdges.push(edge);
      }
    }
  }

  // Detect collisions: same raw ID in different spec dirs
  const idToDirs = new Map<string, Set<string>>();
  for (const req of collected) {
    const dirs = idToDirs.get(req.id) ?? new Set();
    dirs.add(req.specDir);
    idToDirs.set(req.id, dirs);
  }

  const collidingIds = new Set<string>();
  for (const [id, dirs] of idToDirs) {
    if (dirs.size > 1) {
      collidingIds.add(id);
    }
  }

  // Pass 2: register nodes with qualified IDs for collisions
  const idMapping = new Map<string, string>();

  for (const req of collected) {
    let finalId: string;
    if (collidingIds.has(req.id)) {
      finalId = `${req.specDir}/${req.id}`;
    } else {
      finalId = req.id;
    }

    idMapping.set(`${req.specDir}/${req.id}`, finalId);

    const node: GraphNode = {
      ...req.node,
      id: finalId,
    };

    const existing = nodes.get(finalId);
    if (existing && existing.filePath !== node.filePath) {
      warnings.push({
        type: "duplicate-id",
        id: finalId,
        files: [existing.filePath, node.filePath],
      });
    }
    nodes.set(finalId, node);

    for (const edge of req.edges) {
      edges.push({
        ...edge,
        source: edge.source === req.id ? finalId : edge.source,
        target: edge.target === req.id ? finalId : edge.target,
      });
    }
  }

  for (const node of nonReqNodes) {
    addNodeWithDupCheck(nodes, node, warnings);
  }

  // Remap non-req edge targets that reference colliding IDs
  for (const edge of nonReqEdges) {
    const remappedTarget = remapId(edge.target, idMapping, collidingIds);
    if (collidingIds.has(edge.target) && remappedTarget === edge.target) {
      const dirs = idToDirs.get(edge.target)!;
      warnings.push({
        type: "ambiguous-id",
        id: edge.target,
        files: [...dirs],
      });
    }
    edges.push({ ...edge, target: remappedTarget });
  }

  // Parse TypeScript files
  const codePatterns = [...config.include, ...config.testPatterns];
  const tsParser = createTSParser(rootDir, codePatterns);
  const tsResult = tsParser.parse();

  for (const node of tsResult.nodes) {
    addNodeWithDupCheck(nodes, node, warnings);
  }

  // Remap @impl/@verifies edge targets for colliding IDs
  for (const edge of tsResult.edges) {
    if ((edge.kind === "implements" || edge.kind === "verifies") && collidingIds.has(edge.target)) {
      const dirs = idToDirs.get(edge.target)!;
      warnings.push({
        type: "ambiguous-id",
        id: edge.target,
        files: [...dirs],
      });
    } else if (
      (edge.kind === "implements" || edge.kind === "verifies") &&
      edge.target.includes("/")
    ) {
      if (!nodes.has(edge.target)) {
        warnings.push({
          type: "ambiguous-id",
          id: edge.target,
          files: [],
        });
      }
      edges.push(edge);
    } else {
      edges.push(edge);
    }
  }

  // T045: Generate contains edges (doc -> req within the same file)
  // Use autoContains alone; doc nodes with explicit node_id exist even when autoNodes=false
  if (autoContains) {
    const docNodes = [...nodes.values()].filter((n) => n.kind === "doc");
    for (const doc of docNodes) {
      for (const [reqId, reqNode] of nodes) {
        if (reqNode.kind === "req" && reqNode.filePath === doc.filePath) {
          edges.push({
            source: doc.id,
            target: reqId,
            kind: "contains",
          });
        }
      }
    }
  }

  // T036: Convert ParseWarnings to BuildWarnings
  for (const pw of parseWarnings) {
    if (pw.type === "invalid-relation") {
      warnings.push({
        type: "invalid-relation",
        id: pw.key,
        files: [pw.filePath],
        message: `unknown relation key. Use "derives_from" or "depends_on"`,
      });
    }
  }

  // T035: orphan-doc warning - check that doc->doc edge targets exist
  // Only fire when the target is missing AND the target would be a doc node.
  // Skip when the target exists as a non-doc node (e.g. req) — that's a valid cross-kind reference.
  for (const edge of edges) {
    if (
      (edge.kind === "derives_from" || edge.kind === "depends_on") &&
      nodes.get(edge.source)?.kind === "doc"
    ) {
      const targetNode = nodes.get(edge.target);
      if (targetNode && targetNode.kind !== "doc") {
        // Target exists but is not a doc node (e.g. req) — not an orphan-doc situation
        continue;
      }
      if (!targetNode) {
        const sourceNode = nodes.get(edge.source)!;
        warnings.push({
          type: "orphan-doc",
          id: edge.target,
          files: [sourceNode.filePath],
          message: `referenced from ${sourceNode.filePath} but not found in graph`,
        });
      }
    }
  }

  // T037: Edge deduplication (FR-006)
  const edgeKey = (e: GraphEdge) => `${e.source}|${e.target}|${e.kind}`;
  const seen = new Set<string>();
  const dedupedEdges: GraphEdge[] = [];
  for (const edge of edges) {
    const key = edgeKey(edge);
    if (!seen.has(key)) {
      seen.add(key);
      dedupedEdges.push(edge);
    }
  }

  return { graph: { nodes, edges: dedupedEdges }, warnings };
}

function extractSpecDir(relFilePath: string, specDirs: string[]): string {
  for (const specDir of specDirs) {
    if (relFilePath.startsWith(specDir + "/")) {
      const rest = relFilePath.slice(specDir.length + 1);
      const parts = rest.split("/");
      if (parts.length > 1) {
        return parts[0];
      }
    }
  }
  return basename(dirname(relFilePath));
}

function remapId(id: string, idMapping: Map<string, string>, collidingIds: Set<string>): string {
  if (!collidingIds.has(id)) return id;

  // Try to find a unique mapping
  const matches: string[] = [];
  for (const [qualifiedKey, finalId] of idMapping) {
    if (qualifiedKey.endsWith(`/${id}`)) {
      matches.push(finalId);
    }
  }

  // If ambiguous, return as-is (warning already emitted or will be)
  return matches.length === 1 ? matches[0] : id;
}

function addNodeWithDupCheck(
  nodes: Map<string, GraphNode>,
  node: GraphNode,
  warnings: BuildWarning[],
) {
  const existing = nodes.get(node.id);
  if (existing && existing.filePath !== node.filePath) {
    warnings.push({
      type: "duplicate-id",
      id: node.id,
      files: [existing.filePath, node.filePath],
    });
  }
  nodes.set(node.id, node);
}
