import { resolve, relative, basename, dirname } from "node:path";
import { globSync } from "glob";
import { parseMarkdown, type ParseWarning } from "../parsers/markdown.js";
import { createTSParser } from "../parsers/typescript.js";
import type { ArtifactGraph, GraphNode, GraphEdge, ArtgraphConfig } from "../types.js";

export interface BuildWarning {
  type: "duplicate-id" | "ambiguous-id" | "orphan-doc" | "invalid-relation" | "reserved-prefix";
  id: string;
  files: string[];
  message?: string;
}

interface CollectedReq {
  id: string;
  specDir: string;
  node: GraphNode;
  edges: GraphEdge[];
}

// Fixed convention presets (C-3). Each entry is a [from, to] pair of file-name
// stems (lower-cased, extension-stripped) within the *same directory*; when both
// files exist a `derives_from` edge is generated from the `from` doc to the `to`
// doc. A single flat list is sufficient because mixing SDD tools in one
// directory is rare.
//
//   kiro:     design→requirements, tasks→design
//   spec-kit: plan→spec, tasks→plan, research→spec
//
// Note: the shared `tasks` stem produces *both* `tasks→design` and `tasks→plan`
// when a directory happens to contain both `design.md` and `plan.md`. The dedup
// step (key: `source|target|kind`) does NOT collapse these, since the targets
// differ. This is intentional — a directory advertising both tools genuinely
// has two parent chains — but downstream consumers (e.g. `lock.ts`) will see
// `tasks` listed under both `design` and `plan`. See the `mixed dir` test in
// builder.test.ts for the locked-in behavior.
//
// User-defined presets are intentionally omitted (YAGNI) until there is demand.
const CONVENTION_EDGES: ReadonlyArray<readonly [from: string, to: string]> = [
  // kiro
  ["design", "requirements"],
  ["tasks", "design"],
  // spec-kit
  ["plan", "spec"],
  ["tasks", "plan"],
  ["research", "spec"],
];

export function buildGraph(
  rootDir: string,
  config: ArtgraphConfig,
): { graph: ArtifactGraph; warnings: BuildWarning[] } {
  const nodes = new Map<string, GraphNode>();
  const edges: GraphEdge[] = [];
  const warnings: BuildWarning[] = [];

  const autoNodes = config.docGraph?.autoNodes ?? true;
  const autoContains = config.docGraph?.autoContains ?? true;
  const RESERVED_PREFIXES = ["doc:", "file:", "test:", "symbol:"];
  const parseWarnings: ParseWarning[] = [];

  // Pass 1: collect all req nodes and detect collisions
  const collected: CollectedReq[] = [];
  const nonReqNodes: GraphNode[] = [];
  const nonReqEdges: GraphEdge[] = [];

  for (const specDirName of config.specDirs) {
    const specFiles = globSync(resolve(rootDir, specDirName, "**/*.md"));
    for (const file of specFiles) {
    const result = parseMarkdown(file, { rootDir, specDirPrefix: specDirName, reqPatterns: config.reqPatterns });
    const relFile = relative(rootDir, file);
    const specDir = extractSpecDir(relFile, config.specDirs);
    // Compute what the auto-generated doc ID would be for this file
    const specDirRelPath = relFile.startsWith(specDirName + "/")
      ? relFile.slice(specDirName.length + 1)
      : relFile;
    const expectedAutoDocId = `doc:${specDirRelPath}`;

    // Collect parse warnings
    parseWarnings.push(...result.warnings);

    for (const node of result.nodes) {
      if (node.kind === "req") {
        // T028: reserved-prefix warning
        if (RESERVED_PREFIXES.some((p) => node.id.startsWith(p))) {
          const prefix = RESERVED_PREFIXES.find((p) => node.id.startsWith(p))!;
          warnings.push({
            type: "reserved-prefix",
            id: node.id,
            files: [node.filePath],
            message: `req ID uses reserved prefix "${prefix}". This may conflict with auto-generated node IDs`,
          });
        }
        collected.push({ id: node.id, specDir, node, edges: [] });
      } else if (node.kind === "doc") {
        // T027: autoNodes filter - skip auto-generated doc nodes when disabled
        const isAutoGenerated = node.id === expectedAutoDocId;
        if (!autoNodes && isAutoGenerated) {
          continue;
        }
        nonReqNodes.push(node);
      } else {
        nonReqNodes.push(node);
      }
    }

    for (const edge of result.edges) {
      const isFromReq = collected.some((c) => c.node.id === edge.source || c.id === edge.source);
      if (isFromReq) {
        const req = collected.find((c) => c.node.id === edge.source || c.id === edge.source);
        if (req) req.edges.push(edge);
      } else {
        nonReqEdges.push(edge);
      }
    }
  }
  }

  // Detect collisions: same raw ID in different spec dirs
  const idToDirs = new Map<string, Set<string>>();
  for (const req of collected) {
    const dirs = idToDirs.get(req.id) ?? new Set();
    dirs.add(req.specDir);
    idToDirs.set(req.id, dirs);
  }

  const collidingIds = new Set<string>();
  for (const [id, dirs] of idToDirs) {
    if (dirs.size > 1) {
      collidingIds.add(id);
    }
  }

  // Pass 2: register nodes with qualified IDs for collisions
  const idMapping = new Map<string, string>();

  for (const req of collected) {
    let finalId: string;
    if (collidingIds.has(req.id)) {
      finalId = `${req.specDir}/${req.id}`;
    } else {
      finalId = req.id;
    }

    idMapping.set(`${req.specDir}/${req.id}`, finalId);

    const node: GraphNode = {
      ...req.node,
      id: finalId,
    };

    const existing = nodes.get(finalId);
    if (existing && existing.filePath !== node.filePath) {
      warnings.push({
        type: "duplicate-id",
        id: finalId,
        files: [existing.filePath, node.filePath],
      });
    }
    nodes.set(finalId, node);

    for (const edge of req.edges) {
      edges.push({
        ...edge,
        source: edge.source === req.id ? finalId : edge.source,
        target: edge.target === req.id ? finalId : edge.target,
      });
    }
  }

  for (const node of nonReqNodes) {
    addNodeWithDupCheck(nodes, node, warnings);
  }

  // Remap non-req edge targets that reference colliding IDs
  for (const edge of nonReqEdges) {
    const remappedTarget = remapId(edge.target, idMapping, collidingIds);
    if (collidingIds.has(edge.target) && remappedTarget === edge.target) {
      const dirs = idToDirs.get(edge.target)!;
      warnings.push({
        type: "ambiguous-id",
        id: edge.target,
        files: [...dirs],
      });
    }
    edges.push({ ...edge, target: remappedTarget });
  }

  // Parse TypeScript files
  const codePatterns = [...config.include, ...config.testPatterns];
  const tsParser = createTSParser(
    rootDir,
    codePatterns,
    config.mode ?? "file",
    config.reqPatterns?.codeId,
  );
  const tsResult = tsParser.parse();

  for (const node of tsResult.nodes) {
    addNodeWithDupCheck(nodes, node, warnings);
  }

  // Remap @impl/@verifies edge targets for colliding IDs
  for (const edge of tsResult.edges) {
    if ((edge.kind === "implements" || edge.kind === "verifies") && collidingIds.has(edge.target)) {
      const dirs = idToDirs.get(edge.target)!;
      warnings.push({
        type: "ambiguous-id",
        id: edge.target,
        files: [...dirs],
      });
    } else if (
      (edge.kind === "implements" || edge.kind === "verifies") &&
      edge.target.includes("/")
    ) {
      if (!nodes.has(edge.target)) {
        warnings.push({
          type: "ambiguous-id",
          id: edge.target,
          files: [],
        });
      }
      edges.push(edge);
    } else {
      edges.push(edge);
    }
  }

  // T045: Generate contains edges (doc -> req within the same file)
  // Use autoContains alone; doc nodes with explicit node_id exist even when autoNodes=false
  if (autoContains) {
    const docNodes = [...nodes.values()].filter((n) => n.kind === "doc");
    for (const doc of docNodes) {
      for (const [reqId, reqNode] of nodes) {
        if (reqNode.kind === "req" && reqNode.filePath === doc.filePath) {
          edges.push({
            source: doc.id,
            target: reqId,
            kind: "contains",
          });
        }
      }
    }
  }

  // C-3: Infer doc→doc derives_from edges from folder/file-name conventions.
  // Runs at builder level (not the parser) since it needs all doc nodes across
  // directories. Duplicates of frontmatter-declared edges are collapsed by the
  // dedup step below.
  if (config.docGraph?.autoConventions ?? true) {
    edges.push(...inferConventionEdges(nodes));
  }

  // T036: Convert ParseWarnings to BuildWarnings
  for (const pw of parseWarnings) {
    if (pw.type === "invalid-relation") {
      warnings.push({
        type: "invalid-relation",
        id: pw.key,
        files: [pw.filePath],
        message: `unknown relation key. Use "derives_from" or "depends_on"`,
      });
    }
  }

  // T035: orphan-doc warning - check that doc->doc edge targets exist
  // Only fire when the target is missing AND the target would be a doc node.
  // Skip when the target exists as a non-doc node (e.g. req) — that's a valid cross-kind reference.
  for (const edge of edges) {
    if (
      (edge.kind === "derives_from" || edge.kind === "depends_on") &&
      nodes.get(edge.source)?.kind === "doc"
    ) {
      const targetNode = nodes.get(edge.target);
      if (targetNode && targetNode.kind !== "doc") {
        // Target exists but is not a doc node (e.g. req) — not an orphan-doc situation
        continue;
      }
      if (!targetNode) {
        const sourceNode = nodes.get(edge.source)!;
        warnings.push({
          type: "orphan-doc",
          id: edge.target,
          files: [sourceNode.filePath],
          message: `referenced from ${sourceNode.filePath} but not found in graph`,
        });
      }
    }
  }

  // T037: Edge deduplication (FR-006)
  const edgeKey = (e: GraphEdge) => `${e.source}|${e.target}|${e.kind}`;
  const seen = new Set<string>();
  const dedupedEdges: GraphEdge[] = [];
  for (const edge of edges) {
    const key = edgeKey(edge);
    if (!seen.has(key)) {
      seen.add(key);
      dedupedEdges.push(edge);
    }
  }

  return { graph: { nodes, edges: dedupedEdges }, warnings };
}

// Generate `derives_from` edges by matching known file-name conventions within
// each directory. Doc nodes are grouped by their containing directory so that a
// Spec Kit `specs/NNN-feature/` subdir is treated as its own unit. File-name
// matching is case-insensitive (the stem is lower-cased before lookup). Only
// `.md` files participate, because doc-node collection itself globs `**/*.md`.
function inferConventionEdges(nodes: Map<string, GraphNode>): GraphEdge[] {
  // dir -> (file-name stem -> doc node id). The actual node id is used (honoring
  // frontmatter `node_id` overrides), not the raw path.
  const byDir = new Map<string, Map<string, string>>();
  for (const node of nodes.values()) {
    if (node.kind !== "doc") continue;
    const dir = dirname(node.filePath);
    const stem = basename(node.filePath).replace(/\.[^.]*$/, "").toLowerCase();
    let stems = byDir.get(dir);
    if (!stems) {
      stems = new Map();
      byDir.set(dir, stems);
    }
    // If two files share a stem (collision via casing, e.g. Design.md +
    // design.md), keep the first encountered — generating edges for both
    // would be ambiguous.
    if (!stems.has(stem)) stems.set(stem, node.id);
  }

  const edges: GraphEdge[] = [];
  for (const stems of byDir.values()) {
    for (const [fromStem, toStem] of CONVENTION_EDGES) {
      const source = stems.get(fromStem);
      const target = stems.get(toStem);
      // Only emit when both endpoints exist, so no orphan-doc is ever produced.
      if (source && target && source !== target) {
        edges.push({ source, target, kind: "derives_from" });
      }
    }
  }
  return edges;
}

function extractSpecDir(relFilePath: string, specDirs: string[]): string {
  for (const specDir of specDirs) {
    if (relFilePath.startsWith(specDir + "/")) {
      const rest = relFilePath.slice(specDir.length + 1);
      const parts = rest.split("/");
      if (parts.length > 1) {
        return parts[0];
      }
    }
  }
  return basename(dirname(relFilePath));
}

function remapId(id: string, idMapping: Map<string, string>, collidingIds: Set<string>): string {
  if (!collidingIds.has(id)) return id;

  // Try to find a unique mapping
  const matches: string[] = [];
  for (const [qualifiedKey, finalId] of idMapping) {
    if (qualifiedKey.endsWith(`/${id}`)) {
      matches.push(finalId);
    }
  }

  // If ambiguous, return as-is (warning already emitted or will be)
  return matches.length === 1 ? matches[0] : id;
}

function addNodeWithDupCheck(
  nodes: Map<string, GraphNode>,
  node: GraphNode,
  warnings: BuildWarning[],
) {
  const existing = nodes.get(node.id);
  if (existing && existing.filePath !== node.filePath) {
    warnings.push({
      type: "duplicate-id",
      id: node.id,
      files: [existing.filePath, node.filePath],
    });
  }
  nodes.set(node.id, node);
}
